name       : lastpass-cli
version    : 1.2.1
release    : 4
source     :
    - https://github.com/lastpass/lastpass-cli/archive/v1.2.1.tar.gz : 1a49a37a67a973296e218306e6d36c9383347b1833e5a878ebc08355b1c77456
license    : GPL-2.0
component  : network.clients
summary    : CLI for Lastpass.com
description: |
    CLI for Lastpass.com
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libxslt)
    - asciidoc
build      : |
    %cmake
install    : |
    %make_install install-doc
