name       : lastpass-cli
version    : 1.1.2
release    : 2
source     :
    - https://github.com/lastpass/lastpass-cli/archive/v1.1.2.tar.gz : bc737d8e6d713c8aecdfb7f34b29aa9a8ae9b1e9ba80b31059686b18591a8c39
license    : GPL-2.0
component  : network.clients
summary    : CLI for Lastpass.com
description: |
    CLI for Lastpass.com
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libxslt)
    - asciidoc
build      : |
    %cmake
install    : |
    %make_install
    %make install-doc
