name       : lastpass-cli
version    : 1.2.0
release    : 3
source     :
    - https://github.com/lastpass/lastpass-cli/archive/v1.2.0.tar.gz : 17bd9413933ac34d86793c38578298c122835a85132b827fb2fc782b24034aef
license    : GPL-2.0
component  : network.clients
summary    : CLI for Lastpass.com
description: |
    CLI for Lastpass.com
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libxslt)
    - asciidoc
build      : |
    %cmake
install    : |
    %make_install install-doc
