name       : lastpass-cli
version    : 1.3.0
release    : 6
source     :
    - https://github.com/lastpass/lastpass-cli/archive/v1.3.0.tar.gz : bbcfd673d668287e773eef44da65fbd2f292daa213a39528f31037c528dbcfe4
license    : GPL-2.0-or-later
component  : network.clients
summary    : CLI for Lastpass.com
description: |
    CLI for Lastpass.com
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libxslt)
    - asciidoc
build      : |
    %cmake
install    : |
    %make_install install-doc
