name       : lastpass-cli
version    : 1.3.4
release    : 10
source     :
    - https://github.com/lastpass/lastpass-cli/archive/v1.3.4.tar.gz : f747e42dac3441131f9ebf0c119f27c57e8701968de7718224c2cdeb91300b6b
license    : GPL-2.0-or-later
component  : network.clients
summary    : CLI for Lastpass.com
description: |
    CLI for Lastpass.com
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libxslt)
    - asciidoc
setup      : |
    %patch -p1 -i $pkgfiles/0001-Mark-global-variable-as-extern.patch

    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install install-doc

    # Install additional shell completions
    install -Dpm0644 contrib/completions-lpass.fish \
        $installdir/usr/share/fish/vendor_functions.d/lpass.fish
    install -Dpm0644 contrib/lpass_zsh_completion \
        $installdir/usr/share/zsh/site-functions/_lpass
