name       : lastpass-cli
version    : 1.3.2
release    : 8
source     :
    - https://github.com/lastpass/lastpass-cli/archive/v1.3.2.tar.gz : 755338967d8bf39b8c6c9cf46f265896122c01b8e8453e4310ec043d63d8337a
license    : GPL-2.0-or-later
component  : network.clients
summary    : CLI for Lastpass.com
description: |
    CLI for Lastpass.com
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libxslt)
    - asciidoc
build      : |
    %cmake
install    : |
    %make_install install-doc
